Generate a new default 'karmic' VM (using 'server-flavor' kernel) and save it as lzma. Update regression tests to match new image. Minor cleanup on BSD init scripts

diff --git a/data/vmbuild b/data/vmbuild
--- a/data/vmbuild
+++ b/data/vmbuild
@@ -1,6 +1,7 @@
 #!/bin/bash
 dist=$1
 img=$2
+export LANG=
 
 if [[ x$1 == x || x$2 == x ]]; then
     echo "Usage: $0 dist img"
@@ -18,24 +19,55 @@ if [[ -e $img.bz2 ]]; then
     exit 0
 fi
 
-sudo apt-get install python-vm-builder
-sudo vmbuilder kvm ubuntu \
+if [[ -e $img.lzma ]]; then
+    echo "Uncompressing $img.lzma"
+    lzma -d -c $img.lzma > $img
+    exit 0
+fi
+
+# iso="--iso=/net/iso/ubuntu-9.10-server-amd64.iso"
+
+sudo apt-get install python-vm-builder lzma ubuntu-vm-builder
+
+sudo ubuntu-vm-builder kvm $dist \
     -v -o -d $dist \
     --arch=amd64 \
-    --iso=$HOME/ubuntu-9.10-server-amd64.iso \
+	--tmpfs=- \
+	$iso \
     --mirror=http://fr.archive.ubuntu.com/ubuntu \
     --suite=$dist \
-    --flavour=generic \
+    --flavour=server \
     --hostname=cotson \
     --user=user --name=user --pass=user \
     --rootpass=root \
     --rootsize=1024 \
     --swapsize=32 \
+	--debug \
     --addpkg=build-essential
+
+#sudo vmbuilder kvm ubuntu \
+#    -v -o -d $dist \
+#    --arch=amd64 \
+#	$iso \
+#    --mirror=http://fr.archive.ubuntu.com/ubuntu \
+#    --suite=$dist \
+#    --flavour=server \
+#    --hostname=cotson \
+#    --user=user --name=user --pass=user \
+#    --rootpass=root \
+#    --rootsize=1024 \
+#    --swapsize=32 \
+#    --addpkg=build-essential
 
 # --in-place \
 # --variant=minbase \
 
-kvm-img convert -O raw $dist/disk0.qcow2 $img
-bzip2 -9 -c $img > $img.bz2
+if [ -f $dist/disk0.qcow2 ]; then
+    kvm-img convert -O raw $dist/disk0.qcow2 $img
+    lzma --best -c $img > $img.lzma
+    # bzip2 -9 -c $img > $img.bz2
+else
+    echo "ERROR: Cannot find VM!"
+	exit 1
+fi
 
